#配置mysql连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?userUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

#配置mybatis
mybatis:
  #配置xml映射路径
  mapper-locations: classpath:mapper/*.xml
  #配置实体类的别名
  type-aliases-package: com.ray.mybatis.entity
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true
